# Generated by Django 5.0.6 on 2024-06-13 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0004_alter_cliente_id_alter_empleado_id_alter_producto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='email',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
